import {
  Customer,
  Loan,
  FinancialHealth,
  Decision,
  AuditEntry,
  Feedback,
  SystemAnalytics,
} from '../types';

export const MOCK_CUSTOMERS: Customer[] = [
  {
    customer_id: 'C1001',
    name: 'Aarav Patel',
    age: 32,
    preferred_language: 'en',
    monthly_income: 75000,
    consent: { behavioral_trend_analysis: true, anomaly_analysis: true, vernacular_assistance: true },
    created_at: '2026-06-01T00:00:00Z',
  },
  {
    customer_id: 'C1002',
    name: 'Meera Sharma',
    age: 24,
    preferred_language: 'hi',
    monthly_income: 35000,
    consent: { behavioral_trend_analysis: true, anomaly_analysis: true, vernacular_assistance: false },
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    customer_id: 'C1003',
    name: 'Priya Nair',
    age: 27,
    preferred_language: 'en',
    monthly_income: 55000,
    consent: { behavioral_trend_analysis: true, anomaly_analysis: true, vernacular_assistance: true },
    created_at: '2026-06-01T00:00:00Z',
  },
  {
    customer_id: 'C1004',
    name: 'Rohan Deshmukh',
    age: 35,
    preferred_language: 'hi',
    monthly_income: 60000,
    consent: { behavioral_trend_analysis: true, anomaly_analysis: true, vernacular_assistance: true },
    created_at: '2026-06-01T00:00:00Z',
  },
  {
    customer_id: 'C1005',
    name: 'Sana Iqbal',
    age: 29,
    preferred_language: 'gu',
    monthly_income: 42000,
    consent: { behavioral_trend_analysis: true, anomaly_analysis: true, vernacular_assistance: true },
    created_at: '2026-06-01T00:00:00Z',
  },
  {
    customer_id: 'C1006',
    name: 'Kavya Menon',
    age: 31,
    preferred_language: 'en',
    monthly_income: 90000,
    consent: { behavioral_trend_analysis: true, anomaly_analysis: true, vernacular_assistance: false },
    created_at: '2026-06-01T00:00:00Z',
  },
  {
    customer_id: 'C1007',
    name: 'Devika Rao',
    age: 41,
    preferred_language: 'hi',
    monthly_income: 45000,
    consent: { behavioral_trend_analysis: true, anomaly_analysis: true, vernacular_assistance: true },
    created_at: '2026-06-01T00:00:00Z',
  },
];

export const MOCK_LOANS: Record<string, Loan[]> = {
  C1001: [
    {
      loan_id: 'L1001',
      customer_id: 'C1001',
      principal: 250000,
      outstanding: 180000,
      monthly_emi: 9000,
      annual_interest_rate: 11.5,
      remaining_months: 24,
    },
  ],
  C1004: [
    {
      loan_id: 'L1004',
      customer_id: 'C1004',
      principal: 480000,
      outstanding: 410000,
      monthly_emi: 22000,
      annual_interest_rate: 14.5,
      remaining_months: 28,
    },
  ],
  C1005: [
    {
      loan_id: 'L1005',
      customer_id: 'C1005',
      principal: 90000,
      outstanding: 60000,
      monthly_emi: 3000,
      annual_interest_rate: 12.0,
      remaining_months: 20,
    },
  ],
};

export const MOCK_FINANCIAL_HEALTH: Record<string, FinancialHealth> = {
  C1001: {
    customer_id: 'C1001',
    emi_to_income_ratio: 0.12,
    savings_rate: 0.18,
    expense_to_income_ratio: 0.65,
    balance_trend: 'DETERIORATING',
    income_stability: 0.95,
    history_months: 4,
    confidence: 0.88,
  },
  C1002: {
    customer_id: 'C1002',
    emi_to_income_ratio: 0.0,
    savings_rate: 0.25,
    expense_to_income_ratio: 0.40,
    balance_trend: 'STABLE',
    income_stability: 0.80,
    history_months: 1,
    confidence: 0.45, // Low confidence due to thin history
  },
  C1003: {
    customer_id: 'C1003',
    emi_to_income_ratio: 0.0,
    savings_rate: 0.32,
    expense_to_income_ratio: 0.48,
    balance_trend: 'IMPROVING',
    income_stability: 0.98,
    history_months: 4,
    confidence: 0.92,
  },
  C1004: {
    customer_id: 'C1004',
    emi_to_income_ratio: 0.367, // ~37% EMI burden
    savings_rate: 0.08,  // < 10%
    expense_to_income_ratio: 0.78,
    balance_trend: 'DETERIORATING',
    income_stability: 0.92,
    history_months: 4,
    confidence: 0.87,
  },
  C1005: {
    customer_id: 'C1005',
    emi_to_income_ratio: 0.071,
    savings_rate: 0.15,
    expense_to_income_ratio: 0.52,
    balance_trend: 'STABLE',
    income_stability: 0.90,
    history_months: 3,
    confidence: 0.85,
  },
  C1006: {
    customer_id: 'C1006',
    emi_to_income_ratio: 0.0,
    savings_rate: 0.28,
    expense_to_income_ratio: 0.45,
    balance_trend: 'STABLE',
    income_stability: 0.96,
    history_months: 3,
    confidence: 0.90,
  },
  C1007: {
    customer_id: 'C1007',
    emi_to_income_ratio: 0.0,
    savings_rate: 0.18,
    expense_to_income_ratio: 0.60,
    balance_trend: 'STABLE',
    income_stability: 0.91,
    history_months: 4,
    confidence: 0.89,
  },
};

export const MOCK_DECISIONS: Record<string, Decision> = {
  C1001: {
    decision_id: 'DEC-1001',
    customer_id: 'C1001',
    decision: 'VERIFY',
    confidence: 0.88,
    reason_codes: ['UNUSUAL_TRANSACTION'],
    action: {
      title: 'Verify Transfer Anomaly',
      type: 'VERIFY_TRANSACTION',
      description: 'Transaction TX1017 of ₹95,000 exceeds 80% monthly income baseline.',
      suggested_product: 'Transaction Authentication',
    },
    signals: {
      unusual_transaction_id: 'TX1017',
      unusual_amount: 95000,
      anomaly_score: 0.92,
      emi_to_income_ratio: 0.12,
    },
    policy_version: 'v1.0',
    timestamp: '2026-09-12T10:30:00Z',
  },
  C1002: {
    decision_id: 'DEC-1002',
    customer_id: 'C1002',
    decision: 'NO_ACTION',
    confidence: 0.45,
    reason_codes: ['INSUFFICIENT_HISTORY', 'LOW_DATA_CONFIDENCE'],
    action: null,
    signals: {
      history_months: 1,
      savings_rate: 0.25,
    },
    policy_version: 'v1.0',
    timestamp: '2026-09-12T11:00:00Z',
  },
  C1003: {
    decision_id: 'DEC-1003',
    customer_id: 'C1003',
    decision: 'RECOMMEND',
    confidence: 0.92,
    reason_codes: ['HEALTHY_FINANCIAL_TREND', 'STABLE_INCOME'],
    action: {
      title: 'Tax-Saving Mutual Fund SIP Recommendation',
      type: 'RECOMMEND_INVESTMENT',
      description: 'Disciplined savings history suggests customer could benefit from high-yield liquid mutual fund.',
      suggested_product: 'Bharat Flexi Mutual Fund',
      amount: 5000,
    },
    signals: {
      savings_rate: 0.32,
      history_months: 4,
      balance_trend: 'IMPROVING',
    },
    policy_version: 'v1.0',
    timestamp: '2026-09-12T09:15:00Z',
  },
  C1004: {
    decision_id: 'DEC-1004',
    customer_id: 'C1004',
    decision: 'INTERVENE',
    confidence: 0.87,
    reason_codes: ['HIGH_EMI_BURDEN', 'DECLINING_SAVINGS', 'RISING_EXPENSE_RATIO'],
    action: {
      title: 'Debt Restructuring & EMI Relief Nudge',
      type: 'FINANCIAL_HEALTH_SUPPORT',
      description: 'EMI burden (36.7%) and declining savings rate (8%) require proactive financial counseling support.',
      support_type: 'DEBT_COUNSELING',
    },
    signals: {
      emi_to_income_ratio: 0.367,
      savings_rate: 0.08,
      expense_to_income_ratio: 0.78,
    },
    policy_version: 'v1.0',
    timestamp: '2026-09-12T08:45:00Z',
  },
  C1005: {
    decision_id: 'DEC-1005',
    customer_id: 'C1005',
    decision: 'VERIFY',
    confidence: 0.85,
    reason_codes: ['UNUSUAL_TRANSACTION'],
    action: {
      title: 'Appliance Purchase Verification',
      type: 'VERIFY_PURCHASE',
      description: 'One-off home appliance purchase of ₹36,000 flagged for verification (Anomaly ≠ Fraud).',
      suggested_product: 'Customer Self-Confirmation',
      amount: 36000,
    },
    signals: {
      unusual_transaction_id: 'TX5019',
      unusual_amount: 36000,
      anomaly_score: 0.84,
    },
    policy_version: 'v1.0',
    timestamp: '2026-09-12T07:20:00Z',
  },
  C1006: {
    decision_id: 'DEC-1006',
    customer_id: 'C1006',
    decision: 'VERIFY',
    confidence: 0.90,
    reason_codes: ['UNUSUAL_TRANSACTION'],
    action: {
      title: 'Family Function Expense Check',
      type: 'VERIFY_PURCHASE',
      description: 'Wedding venue advance of ₹75,000 exceeds baseline threshold despite strong income.',
      amount: 75000,
    },
    signals: {
      unusual_transaction_id: 'TX6021',
      unusual_amount: 75000,
      anomaly_score: 0.88,
    },
    policy_version: 'v1.0',
    timestamp: '2026-09-11T16:00:00Z',
  },
  C1007: {
    decision_id: 'DEC-1007',
    customer_id: 'C1007',
    decision: 'NO_ACTION',
    confidence: 0.89,
    reason_codes: ['NO_REASONABLE_BENEFIT'],
    action: null,
    signals: {
      savings_rate: 0.18,
      emi_to_income_ratio: 0.0,
      history_months: 4,
    },
    policy_version: 'v1.0',
    timestamp: '2026-09-11T14:30:00Z',
  },
};

export const MOCK_AUDIT_LOGS: AuditEntry[] = [
  {
    id: 'AUD-001',
    decision_id: 'DEC-1001',
    customer_id: 'C1001',
    decision: 'VERIFY',
    reason_codes: ['UNUSUAL_TRANSACTION'],
    confidence: 0.88,
    policy_version: 'v1.0',
    audit_timestamp: '2026-09-12T10:30:00Z',
    reviewed_by: 'System Intelligence',
  },
  {
    id: 'AUD-002',
    decision_id: 'DEC-1002',
    customer_id: 'C1002',
    decision: 'NO_ACTION',
    reason_codes: ['INSUFFICIENT_HISTORY', 'LOW_DATA_CONFIDENCE'],
    confidence: 0.45,
    policy_version: 'v1.0',
    audit_timestamp: '2026-09-12T11:00:00Z',
    reviewed_by: 'System Intelligence',
  },
  {
    id: 'AUD-003',
    decision_id: 'DEC-1003',
    customer_id: 'C1003',
    decision: 'RECOMMEND',
    reason_codes: ['HEALTHY_FINANCIAL_TREND', 'STABLE_INCOME'],
    confidence: 0.92,
    policy_version: 'v1.0',
    audit_timestamp: '2026-09-12T09:15:00Z',
    reviewed_by: 'System Intelligence',
  },
  {
    id: 'AUD-004',
    decision_id: 'DEC-1004',
    customer_id: 'C1004',
    decision: 'INTERVENE',
    reason_codes: ['HIGH_EMI_BURDEN', 'DECLINING_SAVINGS', 'RISING_EXPENSE_RATIO'],
    confidence: 0.87,
    policy_version: 'v1.0',
    audit_timestamp: '2026-09-12T08:45:00Z',
    reviewed_by: 'System Intelligence',
  },
  {
    id: 'AUD-005',
    decision_id: 'DEC-1005',
    customer_id: 'C1005',
    decision: 'VERIFY',
    reason_codes: ['UNUSUAL_TRANSACTION'],
    confidence: 0.85,
    policy_version: 'v1.0',
    audit_timestamp: '2026-09-12T07:20:00Z',
    reviewed_by: 'System Intelligence',
  },
];

export const MOCK_FEEDBACK: Feedback[] = [
  {
    id: 'FB-001',
    customer_id: 'C1003',
    event_type: 'ENGAGED',
    decision_id: 'DEC-1003',
    metadata: { channel: 'copilot', clicked: 'Bharat Flexi Mutual Fund' },
    created_at: '2026-09-12T09:30:00Z',
  },
  {
    id: 'FB-002',
    customer_id: 'C1004',
    event_type: 'FOLLOW_UP',
    decision_id: 'DEC-1004',
    metadata: { channel: 'sms_nudge', requested_callback: true },
    created_at: '2026-09-12T09:00:00Z',
  },
];

export function getMockAnalytics(): SystemAnalytics {
  return {
    total_customers: MOCK_CUSTOMERS.length,
    decision_counts: {
      RECOMMEND: 1,
      INTERVENE: 1,
      VERIFY: 3,
      NO_ACTION: 2,
    },
    confidence_buckets: {
      high: 5,
      medium: 1,
      low: 1,
    },
    reason_code_counts: {
      UNUSUAL_TRANSACTION: 3,
      INSUFFICIENT_HISTORY: 1,
      HIGH_EMI_BURDEN: 1,
      DECLINING_SAVINGS: 1,
      HEALTHY_FINANCIAL_TREND: 1,
      NO_REASONABLE_BENEFIT: 1,
    },
    no_action_percentage: Math.round((2 / 7) * 100),
    review_queue_count: 3, // C1002 (low conf), C1004 (intervene), C1005 (verify)
  };
}
